name: Add label to new issue

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  label-new-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: context.issue.number
            });

            const statusLabel = issue.data.labels.find(({ name }) =>
              name.startsWith("status:")
            );

            if (statusLabel === undefined) {
              await github.rest.issues.addLabels({
                owner: context.issue.owner,
                repo: context.issue.repo,
                issue_number: context.issue.number,
                labels: ["status:triaging"]
              });
            } else {
              console.log(`Issue already has a status: ${statusLabel.name}`);
            }
